### ISSUE TITLE
DX11 feature level 10.0 is required to run the engine

### ISSUE THREAD

**Issue by danger89** [rkfg/proton-ge-custom#1]
# Compatibility Report
- Name of the game with compatibility issues: Halo: The Master Chief Collection
- Steam AppID of the game:  [976730](https://store.steampowered.com/app/976730/Halo_The_Master_Chief_Collection/)

## System Information
- GPU: Radeon RX 580
- Driver/LLVM version: amdgpu
- Kernel version: 4.15.0-70
- Proton version: Your custom MCC thingy

Log file (using PROTON_LOG=1):
[steam-976730.log](https://github.com/rkfg/proton-ge-custom/files/3937227/steam-976730.log)

Extra info:
```
sudo lshw -c video | grep amdgpu -B 10 -A 1
  *-display                 
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480/570/570X/580/580X]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:02:00.0
       version: e7
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:27 memory:d0000000-dfffffff memory:cfe00000-cfffffff ioport:a000(size=256) memory:fba80000-fbabffff memory:c0000-dffff
```

## Symptoms 

Error message: "DX11 feature level 10.0 is required to run the engine." My GPU supports already DX12, so this should work actually.

![error](https://user-images.githubusercontent.com/628926/70397058-1bb68700-1a0f-11ea-9f62-50c7b3520a8e.png)

## Reproduction

Start 'Halo: The master chief collection' in Steam.

## Questions
 Should I try to install latest mesa drivers or something: https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers?

Does the game(s) requires Vulkan support?

**Comment by rkfg** [comment]
Sorry, can't help with that as I have zero experience with Radeon. The game (DXVK to be precise) indeed needs Vulkan.

**Comment by danger89** [comment]
OK, I read on the internet it could be the anti-cheat software from Halo, causing issues.

Nevertheless, I instead my proposed PPA:
https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

Rather easy:

```sh
sudo add-apt-repository ppa:oibaf/graphics-drivers
sudo apt-get update
sudo apt-get upgrade
```

Install all the required Vulkan/mesa drivers for AMD GPUs:

`sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils`

Now I can test Vulkan using the smoke test, running: `vulkan-smoketest`

![smoke](https://user-images.githubusercontent.com/628926/70444216-d68b6700-1a99-11ea-866b-a9cb3520ca5e.png)

So far so good, keep you posted.

**Comment by danger89** [comment]
Looks like the new mesa & vulkan stuff fixes this issue.
